# Generated by Django 5.0.7 on 2024-10-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
