# Generated by Django 5.0.7 on 2024-10-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0003_totalrevenue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.IntegerField(default=0)),
                ('dishes_served', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='TotalRevenue',
        ),
    ]
