# Generated by Django 5.0.7 on 2024-10-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0004_stats_delete_totalrevenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
