# Generated by Django 5.0.7 on 2024-10-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0005_dish_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='last_modified',
            field=models.DateTimeField(),
        ),
    ]
